pins:
  clk_pin: 13
  dt_pin: 5
  sw_pin: 6

volumio:
  host: localhost
  port: 3000
  api_url: http://localhost:3000/api/v1
  connection_timeout: 5

display:
  default_album_art: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/menus/albumart.jpg
  loading_gif_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/Loading.gif
  ready_gif_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/ready.gif
  ready_new_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/ready_new.gif
  ready_loop_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/ready_loop.gif
  connecting_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/connecting.gif
  connected_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/connected.gif
  updating_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/updating.gif
  updatedmessage_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/updatedmessage.gif
  screensaver_gif_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/screensaver/geo.gif
  logo_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/gif/logo.gif
  shutdown_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/shuttingdown.png
  vuscreen_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/pngs/vuscreen.png
  digitalvuscreen_path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/images/pngs/digitalvuscreen.png
  rotation: 2
  fonts:
    playback_large:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/DSEG7Classic-Light.ttf
      size: 45
    playback_medium:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 18
    playback_small:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 12
    artist_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 12
    song_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 14
      
    DVU_artist_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 10
    DVU_song_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 12
      
    data_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 10
    menu_font:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 10
    menu_font_bold:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Bold.ttf
      size: 10
    clock_large:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/DSEG7Classic-LightItalic.ttf
      size: 35
    sample_rate:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/DSEG7Classic-LightItalic.ttf
      size: 46
    sample_rate_khz:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 12
    volume_small:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 8
    radio_title:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 15
    radio_bitrate:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 10
    radio_small:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 12
    minimal_volume:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/Montserrat-Bold.ttf
      size: 15
    minimal_service:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/Montserrat-Regular.ttf
      size: 27
    minimal_data:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/Montserrat-Regular.ttf
      size: 10
    clock_sans:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 40
    clock_dots:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/led_counter-7.ttf
      size: 40
    clock_digital:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/DSEG7Classic-Light.ttf
      size: 30
    clock_bold:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/Montserrat-Bold.ttf
      size: 42
    clockdate_sans:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/OpenSans-Regular.ttf
      size: 15
    clockdate_dots:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/led_counter-7.ttf
      size: 15
    clockdate_digital:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/DSEG7Classic-Light.ttf
      size: 10
    clockdate_bold:
      path: /data/plugins/system_hardware/quadify/quadifyapp/src/assets/fonts/Montserrat-Regular.ttf
      size: 10
  refresh_rate: 60
  cache_images: true

mcp23017_address: 32

logging:
  level: DEBUG
  log_file: /data/plugins/system_hardware/quadify/quadifyapp/quadifyclean.log
  log_format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
